name: Bug 🐞
description: Report a bug report
labels: [kind/bug]

body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information. 

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system are you on? Please provide the version as well. If you are on a Mac, please specify Apple silicon or Intel."
      placeholder: "macOS Ventura 13.3 (Arm), Windows 11"
    validations:
      required: true 

  - type: input
    id: install
    attributes:
      label: Installation Method
      description: "How did you install Podman Desktop ? With a package manager, with an installer ?"
      placeholder: "Installer from website, Brew(macOS), Winget(Windows), Flathub(Linux), etc."

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      options:
        - "1.0.x"
        - "next (development version)"
        - "0.15.0"
        - "0.14.1"
        - "0.14.0"
        - "0.13.0"
        - "0.12.0"
        - "0.11.0"
        - "0.10.0"
        - "0.9.1"
        - "0.8.0"
        - "0.0.7"
        - "0.0.6"
        - "0.0.5"
        - "0.0.4"
        - "0.0.3"
        - "0.0.2"
        - "0.0.1"
    validations:
      required: true 

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What steps do we need to take to reproduce this error? 

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. 
      render: shell 

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots here.
